title: WIP
name: Kim HongKi
email: your-email@example.com
description: Hi There! Welcome to my first website

baseurl: "/blog"
url: ""

display_footer: inital  #change this to 'none' if you want to hide the footer copyright text

parallax_image_one: assets/images/startup3.jpg # These are the images used for the parallax background
parallax_image_two: assets/images/startup3.jpg

project_one: "Hardware"
project_one_description: Hardwares related to embedded system design. Mainly PCB layout, schematic, key information from datasheet, protocols.
project_one_url: https://github.com/jameshamann/jekyll-material-theme
project_one_icon: location_on
proj1_pic: https://ch3301files.storage.live.com/y4mqaHfqc3M42Ui4FJFKitgzgUyl7NjmNxOougPfkgaFkxYJtaF5iIt4vZQ8Bv-VXaQRplyVrTZfdQxNjmnZK7JCg6ZN_E5ZkNLWcubHEKSB8WVrEL3MX5DJNDz2w5WgEvKGf_2Q9Ms0IIJ0kasd5og2NXs2nOl3WP1T_FhN86YC3O-NLV6YOlLE7sTA7CkZP-p?width=1280&height=960&cropmode=none

project_two: "BSP"
project_two_description: 
project_two_url: https://github.com/jameshamann/jekyll-material-theme
project_two_icon: photo_camera
proj2_pic: https://ch3301files.storage.live.com/y4mNaLwJfUKJItUTyNY9ztvdIH_jhZcgWpXxLUt8qQO2PIrQM35om4sdi04DV94y5Pf8LAQqzrpD6oFrRYsrXtRKDmQC4vt9Qp9AQvVhkc59xFdphoTOHIInwuyZZ8PpnJAyqtf6cq_lIJACRaHqVqUOr1BTrjAmQcU2PLTbF3is970uO9GDda7_L4vBxXPlF6a?width=1280&height=805&cropmode=none

project_three: "Applications"
project_three_description: Describe your project!
project_three_url: https://github.com/jameshamann/jekyll-material-theme
project_three_icon: hotel
proj3_pic: https://ch3301files.storage.live.com/y4mIm-bsu2PF8XziPDhLUZw9qJ1olcrWT6rg6_62tuT-c7O7FxNzpTUHY4PU7uAsHPe3RhBJ4k-7hnw2_4PI6xe1EqnhwOgX6wwnqrHb1CFbDGADXNiM_UGLe5NLJqTwW3Q-wFP8Po7mw0xewYwzw4q3CAhArR1ofxNiLMHuvpzZAKCuEzyQJwcV2W_e7DmKna8?width=4500&height=3000&cropmode=none


project_four: "As a hobbyist"
project_four_description: As an enthusiastic hobbyst, some projects are totally pointless and based on personal appetite!
project_four_url: https://github.com/jameshamann/jekyll-material-theme
project_four_icon: restaurant
proj4_pic: <iframe width="560" height="315" src="https://www.youtube.com/embed/qmQr0Uyi0Ls" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>#https://ch3301files.storage.live.com/y4ma7llOhsa2MPJhxF2_nW8pX1FnSiA1Kfylg0t7zLia36GQfnxjYD3lCF5Cxc_mmd5s-h9t37TkQnH4XUc2ZF_XaqR3GjMFXxoLj13xlXnJfFC_pu-jqBGrpkFMmwrkARUggwhrkIFFAsea_2SCzm1CU0Ps-MzOV8acqA9GPaV17jGbL7i0gP8lxetuVGIsCcT?width=1280&height=853&cropmode=none

portfolio_heading: Hi There!
portfolio_type: cards

syntax_highlighting: true
# Skill icons from https://konpa.github.io/devicon/

skills:
  - name: amazonwebservices
  - name: android
  - name: angularjs
  - name: apache
  - name: appcelerator
  - name: apple
  - name: atom
  - name: babel
  - name: backbonejs
  - name: bitbucket
  - name: bootstrap
  - name: bower
  - name: c
  - name: chrome
  - name: codeigniter
  - name: coffescript
  - name: confluence
  - name: cplusplus
  - name: csharp
  - name: css3
  - name: cucumber
  - name: d3js
  - name: debian
  - name: devicon
  - name: django
  - name: docker
  - name: doctrine
  - name: dot-net
  - name: drupal
  - name: erlang
  - name: facebook
  - name: firefox
  - name: foundation
  - name: gatling
  - name: gimp
  - name: git
  - name: github
  - name: gitlab
  - name: go
  - name: google
  - name: gradle
  - name: grunt
  - name: gulp
  - name: heroku
  - name: html5
  - name: ie10
  - name: illustrator
  - name: inkscape
  - name: itellij
  - name: java
  - name: jasmine
  - name: javascript
  - name: laravel
  - name: less
  - name: linux
  - name: meteor
  - name: mocha
  - name: mongodb
  - name: moodle
  - name: mysql
  - name: nginx
  - name: nodejs
  - name: nodewebkit
  - name: oracle
  - name: photoshop
  - name: php
  - name: phpstorm
  - name: protractor
  - name: postgresql
  - name: python
  - name: pycharm
  - name: rails
  - name: react
  - name: redhat
  - name: redis
  - name: ruby
  - name: rubymine
  - name: safari
  - name: sass
  - name: sequelize
  - name: slack
  - name: sourcetree
  - name: ssh
  - name: swift
  - name: symfony
  - name: tomcat
  - name: travis
  - name: trello
  - name: twitter
  - name: typescript
  - name: ubuntu
  - name: vim
  - name: visualstudio
  - name: vuejs
  - name: webpack
  - name: webstorm
  - name: windows8
  - name: wordpress
  - name: yii
  - name: zend

icon_size: 50 # font-size of icons in px
colored: colored # Leave blank for black and white icons

project_button: Github

github: https://github.com/jameshamann/jekyll-material-theme
medium: https://medium.com

baseurl: # if your site is located at /blog or /home, enter it here, otherwise leave it empty
url: http://localhost:4000/ #the url of your site

# Google tracking, if both are filled, tag manager will prevail. Set up GA through GTM in that case
tag_manager_id: # This looks something like GTM-XXXXXXX
google_analytics_tracking_id: # This looks something like UA-000000000-0 Head over to https://analytics.google.com/ to setup.

cookies_banner: show # The value "show" will show the cookies banner, the value "none" will hide the banner.

cookie_accept_message: All Done!

syntax_highlighting: true # include the css for syntax highlighting

# Build settings
markdown: kramdown
# theme: minima
permalink: pretty
plugins:
  - jekyll-feed
  - jekyll-assets
  - jekyll-minifier
